name: Update Bundle

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2

      - name: Install dependencies
        run: npm install

      - name: Build bundle
        run: npx rollup --config rollup.config.js --configPlugin typescript

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: bundle
          path: output/index.js
