name: Update Bundle

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Set up Node.js
        uses: actions/setup-node@main

      - name: Install dependencies
        run: npm install

      - name: Build bundle
        run: npx rollup --config rollup.config.js --configPlugin typescript

      - name: Remove "export.*" lines from bundle
        run: sed -i '/^export.*/d' output/index.js

      - name: Upload artifact
        uses: actions/upload-artifact@main
        with:
          name: index.js
          path: output/index.js
